@UserSystemId = {{$processEnv USERNAME}}
@baseUrl = https://sam-dev.azus.intactspecialty.net/submission-api/api/v1/submissions

# @name login
POST https://microservices.dev.droot.dmn/security-api/api/security/Login
Content-Type: application/json
usersystemid: {{UserSystemId}}


###
# @name PostSubmissionsEmails
# http://localhost:3000/submissions/inbox
POST {{baseUrl}}/emails
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

{ 
  "from": "dmercado@intactinsurance.com",
  "emailStatusId": 1,
  "externalId": "AAMkADUzZWVlZTQ1LTJiNjAtNDcwNi04NWE0LWY0MTM1YTZlMzEwZABGAAAAAABaOnPV4xYAQpRPU8_vyxj2BwCodTkqqNXVQLAWd286sJYlAABb3YvTAACodTkqqNXVQLAWd286sJYlAAG5DM6QAAA=",
  "receivedDate": "2025-08-13T13:06:25.108Z",
  "source": "Agile Brains Consulting",
  "subject": "ABC Test",
  "sourceAddress": "ybauza@intactinsurance.com"
}


###
# @name GetSubmissionsEmails
GET {{baseUrl}}/emails
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

###
# @name PostSubmission
# http://localhost:3000/submissions/inbox
POST {{baseUrl}}
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

{
  "assignedToId": "DXMERCA",
  "businessUnitId": "I",
  "comment": "Test comment",
  "emailId": 0,
  "externalId": "AAMkADUzZWVlZTQ1LTJiNjAtNDcwNi04NWE0LWY0MTM1YTZlMzEwZABGAAAAAABaOnPV4xYAQpRPU8_vyxj2BwCodTkqqNXVQLAWd286sJYlAABb3YvTAACodTkqqNXVQLAWd286sJYlAAG5DM6QAAA=",
  "source": "Agile Brains Consulting",
  "submissionStatusId": 0,
  "accountId": 0
}

###
# @name GetSubmissionsWorklist
GET {{baseUrl}}?AssignedToId=IXDRAKE
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json
